# -*- coding: utf-8 -*-
"""ResumeBuilder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VC-oXp6Wj8syWdMsCe2tigTB3J3HmZWu
"""

pip install fpdf

from fpdf import FPDF
#simple resume
pdf = FPDF()
pdf.add_page()
#setter
pdf.add_font("PTRegular", "", "PTSerif-Regular.ttf", True)
pdf.add_font("PTBold", "", "PTSerif-Bold.ttf", True)
pdf.set_font("PTRegular", "", 40)
pdf.set_margins(10,10,0)
pdf.set_auto_page_break(True, margin = 25.0)
#function
#experience
def experience(num):
  experienceDict = {"Name":[],
                    "StartYear":[],
                    "EndYear" : [],
                    "Descri": [],
                    "CompanyName":[]}
  for i in range(num):
    ex = input("Job Title for expereince: " + str(i + 1) + " ")
    compName = input("Company Name for job: " + str(i + 1) + " ")
    startDate = input("What year did you start: ")
    endDate = input("What year did you end: ")
    description = input("Enter one or two lines explain your job? ")
    print("\n")
    experienceDict["Name"].append(ex)
    experienceDict["StartYear"].append(startDate)
    experienceDict["EndYear"].append(endDate)
    experienceDict["Descri"].append(description)
    experienceDict["CompanyName"].append(compName)

  for i in range(num):
    pdf.set_font("PTRegular", "", 12)
    pdf.cell(190,6, str(i+1) + ".", ln = 2)
    pdf.set_x(15)
    pdf.cell(190,5, experienceDict["StartYear"][i] + " - " + experienceDict["EndYear"][i], align = "L", ln = 2)
    pdf.set_font("PTBold", "", 12)
    pdf.cell(190,5, experienceDict["Name"][i] + ", " + experienceDict["CompanyName"][i], align = "L", ln = 2)#job name
    pdf.set_font("PTRegular", "", 12)
    pdf.multi_cell(190,7, experienceDict["Descri"][i], align = "L")#job des
    pdf.cell(190,6, "", align = "L", ln = 2)#job name
    pdf.set_x(10)


#education
def education(num):
  educationDict = {"Degree": [],
      "School": [],
      "Descri": [],
      "Month/Yr": []
  }
  for i in range(num):
    degree= input("What degree did you get?")
    school= input("What school did you go?")
    monthYr = input("What MM/YY did you go to this school?")
    descri= input("Description")
    print("\n")
    educationDict["Degree"].append(degree)
    educationDict["School"].append(school)
    educationDict["Descri"].append(descri)
    educationDict["Month/Yr"].append(monthYr)

  for i in range(num):
    pdf.set_font("PTRegular", "", 12)
    pdf.cell(190,6, str(i+1) + ".", ln = 2)
    pdf.set_x(15)
    pdf.cell(190,5, educationDict["Month/Yr"][i], align = "L", ln = 2)
    pdf.set_font("PTBold", "", 12)
    pdf.cell(190,5, educationDict["Degree"][i] + ", " + educationDict["School"][i], align = "L", ln = 2)#job name
    pdf.set_font("PTRegular", "", 12)
    pdf.multi_cell(190,7, educationDict["Descri"][i], align = "L")#job des
    pdf.cell(190,6, "", align = "L", ln = 2)#job name
    pdf.set_x(10)
#activity
def skills(num):
  activities = []
  for i in range(num):
    act = input("What is your " + str(i + 1) + " activity? ")
    activities.append(act)

  for i in range(num):
    pdf.set_font("PTRegular", "", 12)
    pdf.set_x(15)
    pdf.cell(50,7, " • " + activities[i], align = "L", ln = 2)
    pdf.set_x(10)


def simpleResume():
  #defualt cell size(190, 5)
  #cell for title(190, 15)

  firstName = input("First Name ")
  lastName = input("Last Name ")
  address = input("Address:")
  phone = input("Phone:")
  email = input("Email: ")
  description = input("Description: ")
  print("\n")
  #header
  pdf.cell(190, 15, firstName + " " + lastName, align = "C", ln=2) #Name
  pdf.set_font("PTRegular", "", 11)
  pdf.cell(190, 5, address + "  ·  " + phone, align = "C", ln = 2)
  pdf.cell(190, 5,txt ="Email: " + email, align = "C", ln = 2)
  pdf.cell(190, 7,"", align = "C", ln = 2)
  pdf.line(20, 39, 190, 39)
  #description
  pdf.set_text_color(94,94,94)
  pdf.multi_cell(190, 6, description, align = "L")
  pdf.cell(190, 7,"", align = "C", ln = 2)

  #experience
  pdf.set_text_color(0,0,0)
  pdf.set_font("PTBold", "", 15)
  pdf.cell(190, 7, txt = "EXPERIENCE:-", ln = 2)
  exNum = int(input("How many experience do you want to enter? "))
  experience(exNum)

  #education
  pdf.set_text_color(0,0,0)
  pdf.set_font("PTBold", "", 15)
  pdf.cell(190, 7, txt = "EDUCATION:-", ln = 2)
  edNum = int(input("How many education do you want to enter? "))
  education(edNum)

  #skills
  pdf.set_text_color(0,0,0)
  pdf.set_font("PTBold", "", 15)
  pdf.cell(190, 7, txt = "SKILLS:-", ln = 2)
  skillNum = int(input("How many skills do you want to enter? "))
  skills(skillNum)
  print("\n")

  #activtiy
  pdf.set_text_color(0,0,0)
  pdf.set_font("PTBold", "", 15)
  pdf.cell(190, 7, txt = "ACTIVITIES:-", ln = 2)
  pdf.set_text_color(94,94,94)
  pdf.set_font("PTRegular", "", 12)
  act = input("Write a three sentence about your passions and activities? ")
  pdf.multi_cell(190,5, act, align = "L")
  pdf.output(firstName + "'s Resume.pdf")


simpleResume()